# Generated by Django 5.2.14 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('service_date', models.DateField(blank=True, help_text='Gregorian storage for the Jalali service date entered by admin.', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('price_estimate', models.DecimalField(decimal_places=0, default=0, help_text='Estimated price before work starts.', max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=0, default=0, help_text='Final price after work is done.', max_digits=12)),
                ('extra_payment', models.DecimalField(decimal_places=0, default=0, help_text='Additional payment recorded on the order workflow.', max_digits=12)),
                ('wage_deduction', models.DecimalField(decimal_places=0, default=0, help_text='Amount deducted from technician wage for this order.', max_digits=12)),
                ('required_skill', models.CharField(blank=True, help_text='Required skill name for technician matching.', max_length=100)),
                ('priority2_visible_at', models.DateTimeField(blank=True, help_text='When this order becomes visible to priority-2 technicians.', null=True)),
                ('priority3_visible_at', models.DateTimeField(blank=True, help_text='When this order becomes visible to priority-3 technicians.', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Timestamp when a technician accepted this order.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True, help_text='Admin/staff internal note. Not visible to customers.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('number', 'Number'), ('money', 'Money'), ('text', 'Text'), ('bool', 'Boolean')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note about the change.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
