# Generated by Django 5.1.3 on 2026-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='old_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
