# Generated by Django 5.1.3 on 2026-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderstatuslog_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdefinition',
            name='is_technician_wage_applicable',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این آیتم در محاسبه اجرت تکنسین لحاظ می\u200cشود. فقط برای آیتم\u200cهای از نوع عدد (NUMBER) معتبر است.'),
        ),
    ]
