# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for platform owners.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_permissions', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technician',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techniciancategoryskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_skills', to='tenants.companyservicecategory'),
        ),
        migrations.AddField(
            model_name='techniciancategoryskill',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_skills', to='accounts.technician'),
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.technician'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'phone')},
        ),
        migrations.AddConstraint(
            model_name='operatorpermission',
            constraint=models.UniqueConstraint(fields=('company', 'operator', 'permission_key'), name='unique_operator_permission_per_company_operator_key'),
        ),
        migrations.AddConstraint(
            model_name='techniciancategoryskill',
            constraint=models.UniqueConstraint(fields=('technician', 'category'), name='unique_technician_category_skill'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianskill',
            unique_together={('technician', 'name')},
        ),
    ]
