# Generated by Django 5.2.14 on 2026-06-05 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetSMSBillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_admin_payer', models.CharField(choices=[('PLATFORM', 'مالک پلتفرم'), ('COMPANY', 'شرکت')], default='PLATFORM', max_length=20, verbose_name='مدیر شرکت')),
                ('operator_payer', models.CharField(choices=[('PLATFORM', 'مالک پلتفرم'), ('COMPANY', 'شرکت')], default='PLATFORM', max_length=20, verbose_name='اپراتور')),
                ('technician_payer', models.CharField(choices=[('PLATFORM', 'مالک پلتفرم'), ('COMPANY', 'شرکت')], default='PLATFORM', max_length=20, verbose_name='نیروی خدماتی')),
                ('customer_payer', models.CharField(choices=[('PLATFORM', 'مالک پلتفرم'), ('COMPANY', 'شرکت')], default='PLATFORM', max_length=20, verbose_name='مشتری')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_sms_policy', to='tenants.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset SMS Billing Policy',
                'ordering': ['company__name'],
            },
        ),
    ]
