# Generated by Django 5.2.14 on 2026-06-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp_passwordresetsmsbillingpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
