# Generated by Django 5.2.14 on 2026-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='financial_verification_status',
            field=models.CharField(choices=[('not_submitted', 'ارسال نشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تأییدشده'), ('rejected', 'رد شده')], db_index=True, default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='technician',
            name='shaba_number',
            field=models.CharField(blank=True, help_text='شماره شبا: IR + 24 رقم', max_length=26),
        ),
        migrations.AddField(
            model_name='technician',
            name='shaba_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='shaba_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='sub_merchant_id',
            field=models.CharField(blank=True, help_text='شناسه پذیرنده فرعی در درگاه پرداخت — توسط پلتفرم تکمیل می\u200cشود', max_length=100),
        ),
    ]
