# Generated by Django 5.2.14 on 2026-06-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_technician_financial_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_technicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technician',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='verification_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_technicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
