# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('price_yearly', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_technicians', models.PositiveIntegerField(default=10)),
                ('max_orders_per_month', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('COMPANY_REGISTERED', 'ثبت\u200cنام شرکت'), ('COMPANY_APPROVED', 'تأیید شرکت'), ('ORDER_CREATED', 'ایجاد سفارش'), ('ORDER_ASSIGNED', 'تخصیص سفارش'), ('ORDER_STATUS_CHANGED', 'تغییر وضعیت سفارش'), ('INVOICE_CREATED', 'صدور فاکتور'), ('PAYMENT_RECEIVED', 'دریافت پرداخت'), ('SMS_CREDIT_LOW', 'اعتبار پیامک کم'), ('SMS_CREDIT_EMPTY', 'اعتبار پیامک تمام'), ('TECHNICIAN_NOTIFICATION', 'اعلان تکنسین'), ('OPERATOR_NOTIFICATION', 'اعلان اپراتور')], max_length=40)),
                ('channel', models.CharField(choices=[('INTERNAL_NOTIFICATION', 'اعلان داخلی'), ('SMS', 'پیامک'), ('EMAIL_FUTURE', 'ایمیل (آینده)')], max_length=30)),
                ('recipient_type', models.CharField(choices=[('COMPANY_ADMIN', 'مدیر شرکت'), ('OPERATOR', 'اپراتور'), ('TECHNICIAN', 'تکنسین'), ('PLATFORM_OWNER', 'مدیر پلتفرم')], max_length=20)),
                ('title_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('action_url_template', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('allow_company_toggle', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = global default. Set = company-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_templates', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Communication Template',
                'ordering': ['event_key', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'آزمایشی (بدون اتصال)'), ('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('ZIBAL_FUTURE', 'زیبال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)')], default='MOCK', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('merchant_id', models.CharField(blank=True, help_text='Merchant ID or API key (masked in UI)', max_length=200)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('callback_base_url', models.CharField(blank=True, max_length=300)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='tenants.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='CompanySMSWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_rial', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_wallet', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Company SMS Wallet',
            },
        ),
        migrations.CreateModel(
            name='GlobalSMSPricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_per_sms', models.PositiveIntegerField(default=60)),
                ('price_per_sms_rial', models.PositiveIntegerField(default=520)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Pricing Setting',
            },
        ),
        migrations.CreateModel(
            name='PlatformBillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('SMS_RECHARGE', 'شارژ پیامک'), ('SUBSCRIPTION', 'اشتراک'), ('MANUAL', 'دستی'), ('OTHER', 'سایر')], default='SMS_RECHARGE', max_length=20)),
                ('amount_rial', models.BigIntegerField()),
                ('status', models.CharField(choices=[('UNPAID', 'پرداخت نشده'), ('PAID', 'پرداخت شده'), ('CANCELED', 'لغو شده')], default='UNPAID', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_invoices', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_platform_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySMSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'شارژ'), ('DEBIT', 'مصرف'), ('ADJUSTMENT', 'تعدیل'), ('BLOCKED', 'مسدود (اعتبار ناکافی)')], max_length=15)),
                ('amount_rial', models.BigIntegerField()),
                ('sms_parts', models.PositiveIntegerField(default=0)),
                ('message_length', models.PositiveIntegerField(default=0)),
                ('balance_after', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transactions', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='platform_core.companysmswallet')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.platformbillinginvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('PLATFORM_OWNER', 'مدیر پلتفرم'), ('COMPANY', 'شرکت'), ('COMPANY_ADMIN', 'مدیر شرکت'), ('TECHNICIAN', 'تکنسین'), ('CUSTOMER', 'مشتری'), ('CUSTOM', 'سفارشی')], default='COMPANY', max_length=20)),
                ('channel', models.CharField(choices=[('INTERNAL', 'داخلی'), ('SMS_FUTURE', 'پیامک (آینده)'), ('EMAIL_FUTURE', 'ایمیل (آینده)')], default='INTERNAL', max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'دریافتی'), ('OUTBOUND', 'ارسالی')], default='OUTBOUND', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('QUEUED', 'در صف ارسال'), ('SENT', 'ارسال شده'), ('FAILED', 'ناموفق'), ('READ', 'خوانده شده')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_messages', to='tenants.company')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_platform_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='Null if system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_platform_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Message',
                'verbose_name_plural': 'Platform Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'آزمایشی (بدون اتصال)'), ('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('ZIBAL_FUTURE', 'زیبال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)')], default='MOCK', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('merchant_id', models.CharField(blank=True, help_text='Merchant ID or API key (masked in UI)', max_length=200)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('callback_base_url', models.CharField(blank=True, help_text='e.g. https://rastiservice.ir', max_length=300)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='PlatformPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rial', models.BigIntegerField()),
                ('provider', models.CharField(choices=[('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)'), ('OTHER_FUTURE', 'سایر (آینده)')], default='MANUAL', max_length=20)),
                ('authority', models.CharField(blank=True, help_text='Gateway authority/token', max_length=100)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'آغاز شده'), ('REDIRECTED', 'هدایت به درگاه'), ('PAID', 'پرداخت شده'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغو شده'), ('VERIFIED', 'تایید شده')], default='INITIATED', max_length=15)),
                ('gateway_response', models.TextField(blank=True, help_text='Raw gateway response JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payment_transactions', to='tenants.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='platform_core.platformbillinginvoice')),
            ],
            options={
                'verbose_name': 'Platform Payment Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSMSMessageTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت')], max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('payer', models.CharField(choices=[('COMPANY', 'شرکت'), ('PLATFORM', 'مالک پلتفرم')], default='COMPANY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_company_sms_enabled', models.BooleanField(default=True)),
                ('send_start_time', models.TimeField(blank=True, null=True)),
                ('send_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform SMS Message Type Setting',
                'ordering': ['payer', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSMSProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Platform SMS Provider', max_length=100)),
                ('provider_type', models.CharField(choices=[('kavenegar', 'Kavenegar'), ('ghasedak', 'Ghasedak'), ('melipayamak', 'MeliPayamak'), ('fake', 'Fake (Testing)')], default='fake', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('sender_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform SMS Provider Setting',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_core.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplateCompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_template_settings', to='tenants.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='platform_core.communicationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'template'), name='unique_comm_tpl_setting_per_company')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSMSOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت')], max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'در صف ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شده'), ('delivered', 'ارسال موفق'), ('failed', 'ارسال ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('sending_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_sms_messages', to='tenants.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='platform_core.platformsmsprovidersetting')),
            ],
            options={
                'verbose_name': 'Platform SMS Outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='platform_sms_due_idx'), models.Index(fields=['recipient_company', 'template_key'], name='platform_sms_company_key_idx')],
            },
        ),
    ]
