# Generated by Django 5.2.14 on 2026-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsmsmessagetypesetting',
            name='key',
            field=models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت'), ('password_reset', 'بازیابی رمز عبور')], max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='platformsmsoutbox',
            name='template_key',
            field=models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت'), ('password_reset', 'بازیابی رمز عبور')], max_length=80),
        ),
    ]
