# Generated by Django 5.2.14 on 2026-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_platformsitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsmsmessagetypesetting',
            name='key',
            field=models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('subscription_renewed_admin', 'شارژ/تمدید اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت'), ('platform_discount_company_admin', 'کد تخفیف پلتفرم - مدیر شرکت'), ('password_reset', 'بازیابی رمز عبور')], max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='platformsmsoutbox',
            name='template_key',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='body_template',
            field=models.TextField(blank=True, help_text='JSON/Form template اختیاری برای ارسال سفارشی API.'),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='در صورت تغییر API شرکت پیامکی، endpoint از پنل قابل اصلاح است.'),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='headers_template',
            field=models.TextField(blank=True, help_text='JSON اختیاری برای Headerها؛ قابل ویرایش از پنل مالک.'),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='در صورت شکست Provider اصلی، این ارائه\u200cدهنده به عنوان رزرو قابل استفاده است.'),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='عدد کمتر یعنی اولویت بیشتر.'),
        ),
        migrations.AlterField(
            model_name='platformsmsprovidersetting',
            name='success_keywords',
            field=models.CharField(blank=True, help_text='کلمات/کدهای موفقیت، جدا شده با کاما.', max_length=300),
        ),
    ]
