# Generated by Django 5.2.14 on 2026-06-05 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_companyuser_must_change_password_and_more'),
        ('invoices', '0002_initial'),
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('credit', 'بستانکار'), ('debit', 'بدهکار')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('online_gateway', 'پرداخت آنلاین'), ('cash_from_customer', 'نقدی از مشتری (تکنسین)'), ('manual_payment', 'پرداخت دستی'), ('manual_settlement', 'تسویه دستی'), ('direct_gateway_settlement', 'تسویه مستقیم درگاه'), ('adjustment', 'تعدیل'), ('refund', 'بازگشت وجه')], db_index=True, max_length=40)),
                ('amount_rial', models.PositiveBigIntegerField()),
                ('balance_after', models.BigIntegerField(help_text='Running balance after this entry. Positive = company owes tech.')),
                ('description', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='invoices.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.technician')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'technician', 'created_at'], name='ledger_company_tech_date_idx'), models.Index(fields=['company', 'technician', 'entry_type'], name='ledger_company_tech_type_idx')],
            },
        ),
    ]
