# Generated by Django 5.2.14 on 2026-06-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
        ('payments', '0001_initial'),
        ('payouts', '0001_initial'),
        ('tenants', '0002_companyfinancialpolicy_payout_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSplitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('platform_fee_amount', models.PositiveBigIntegerField(default=0)),
                ('company_deposit_amount', models.PositiveBigIntegerField(default=0)),
                ('technician_direct_amount', models.PositiveBigIntegerField(default=0)),
                ('technician_ledger_amount', models.PositiveBigIntegerField(default=0)),
                ('payout_strategy_snapshot', models.CharField(blank=True, max_length=30)),
                ('technician_verified_snapshot', models.BooleanField(default=False)),
                ('technician_sub_merchant_id_snapshot', models.CharField(blank=True, max_length=100)),
                ('platform_fee_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('should_split_with_technician', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('raw_decision', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_snapshots', to='invoices.invoice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_snapshot', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
