# Generated by Django 5.2.14 on 2026-06-05 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
        ("payments", "0001_initial"),
        ("payouts", "0002_paymentsplitsnapshot"),
        ("tenants", "0003_company_merchant_profile_p5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPlatformFeeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("debit", "بدهکار (شرکت به پلتفرم)"),
                            ("credit", "بستانکار (تسویه)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cash_invoice", "فاکتور نقدی"),
                            ("online_gateway", "درگاه آنلاین"),
                            ("manual_adjustment", "تعدیل دستی"),
                            ("platform_fee_settlement", "تسویه کارمزد"),
                            ("refund", "برگشت"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("amount_rial", models.PositiveBigIntegerField()),
                (
                    "balance_after",
                    models.BigIntegerField(
                        help_text="Running balance after this entry. Positive = company still owes platform."
                    ),
                ),
                (
                    "platform_fee_percent_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform fee percent at time of recording.",
                        max_digits=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_fee_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_fee_entries",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_fee_entries",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "created_at"],
                        name="platform_fee_company_date_idx",
                    )
                ],
            },
        ),
    ]
