# Generated by Django 5.1.3 on 2026-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_technicianservicerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianledgerentry',
            name='source',
            field=models.CharField(choices=[('online_gateway', 'پرداخت آنلاین'), ('cash_from_customer', 'نقدی از مشتری (تکنسین)'), ('manual_payment', 'پرداخت دستی'), ('manual_settlement', 'تسویه دستی'), ('direct_gateway_settlement', 'تسویه مستقیم درگاه'), ('adjustment', 'تعدیل'), ('refund', 'بازگشت وجه'), ('technician_service_wage', 'اجرت خدمت تکنسین')], db_index=True, max_length=40),
        ),
    ]
