# Generated by Django 5.2.14 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique per company. Format: INV-<CODE>-<SEQUENCE>', max_length=50)),
                ('public_code', models.CharField(blank=True, db_index=True, help_text='Short public code for read-only invoice sharing.', max_length=24, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('address_snapshot', models.TextField(blank=True)),
                ('technician_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('technician_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('service_title_snapshot', models.CharField(blank=True, max_length=250)),
                ('service_date_snapshot', models.DateField(blank=True, null=True)),
                ('technician_service_wage_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('technician_goods_wage_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('technician_travel_wage_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Legacy total invoice-level discount. Kept in sync with extra + campaign discounts.', max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=0, default=0, help_text='Sum of row gross amounts before row discounts.', max_digits=12)),
                ('row_discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Total discount applied directly on invoice rows.', max_digits=12)),
                ('net_amount_before_invoice_discounts', models.DecimalField(decimal_places=0, default=0, help_text='Gross amount minus row discounts, before extra/campaign discounts.', max_digits=12)),
                ('extra_discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Manual/extra invoice-level discount.', max_digits=12)),
                ('campaign_discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Campaign/discount-code invoice-level discount.', max_digits=12)),
                ('total_discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Total invoice-level discount: extra + campaign.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('settled_service_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_goods_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_travel_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_extra_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_campaign_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_campaign_discount_policy', models.CharField(blank=True, max_length=30, null=True)),
                ('settled_extra_discount_policy', models.CharField(blank=True, max_length=30, null=True)),
                ('settled_technician_gross_share', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_company_gross_share', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_technician_absorbed_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_company_absorbed_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_technician_wage', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_company_share', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('settled_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('settled_payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('settled_discount_code_id', models.PositiveIntegerField(blank=True, help_text='DiscountCode id used at settlement time, stored without FK for audit stability.', null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True, default='مسئولیت فاکتور صادره بر عهده ارائه\u200cدهنده خدمت می\u200cباشد.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('row_type', models.CharField(choices=[('service', 'اجرت خدمات'), ('goods', 'کالا / قطعه'), ('travel', 'ایاب و ذهاب')], default='service', help_text='نوع ردیف برای محاسبه دستمزد تکنسین.', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
