# Generated by Django 5.1.3 on 2026-06-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicecounter_unique_active_invoice_per_order'),
        ('tenants', '0005_company_payment_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecancellationrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company'),
        ),
    ]
