# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text="Unique code used in URLs for tenant resolution. e.g. 'n54'", unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive companies cannot be accessed.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('economic_code', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_discount_policy', models.CharField(choices=[('company', 'Company absorbs discount'), ('technician', 'Technician absorbs discount'), ('half_half', 'Split equally'), ('proportional_share', 'Split by share ratio')], default='company', help_text='Who absorbs campaign/discount-code discounts by default.', max_length=30)),
                ('extra_discount_policy', models.CharField(choices=[('company', 'Company absorbs discount'), ('technician', 'Technician absorbs discount'), ('half_half', 'Split equally'), ('proportional_share', 'Split by share ratio')], default='technician', help_text='Who absorbs extra/manual invoice discounts by default.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_policy', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Company Financial Policy',
                'verbose_name_plural': 'Company Financial Policies',
            },
        ),
        migrations.CreateModel(
            name='CompanyGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='companies/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='Introduction text displayed on the public page.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/pages/logos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='companies/pages/heroes/')),
                ('is_request_form_enabled', models.BooleanField(default=True, help_text='If disabled, visitors cannot submit service requests.')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, help_text='e.g. Saturday-Thursday 9:00-18:00', max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='tenants.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tenants.companyservicecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'Service Subcategories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority2_delay_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before priority-2 technicians see a new order.')),
                ('priority3_delay_minutes', models.PositiveIntegerField(default=60, help_text='Minutes before priority-3 technicians see a new order.')),
                ('show_future_orders_to_technicians', models.BooleanField(default=False, help_text='If True, technicians can see orders scheduled in the future.')),
                ('future_orders_visible_after', models.TimeField(blank=True, default='07:30', help_text='Time of day after which future orders become visible (if enabled).', null=True)),
                ('max_active_orders_per_technician', models.PositiveIntegerField(default=5, help_text='Max concurrent in-progress orders a technician can hold.')),
                ('auto_recycle_cancel_request', models.BooleanField(default=False, help_text='If True, cancelled orders are automatically recycled back to NEW.')),
                ('respect_sms_template_time_window', models.BooleanField(default=True, help_text='If True, SMS messages respect template send_start_time/send_end_time windows.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('preferred_time', models.CharField(blank=True, help_text='Preferred date/time for service.', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='orders.order')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='tenants.companyservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
