# Generated by Django 5.2.14 on 2026-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancialpolicy',
            name='payout_strategy',
            field=models.CharField(choices=[('direct_to_company', 'واریز کامل به حساب شرکت'), ('split_with_technician', 'تسهیم با تکنسین تأییدشده')], default='direct_to_company', help_text='نحوه پرداخت دستمزد تکنسین پس از وصول فاکتور', max_length=30),
        ),
        migrations.AddField(
            model_name='companyfinancialpolicy',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='درصد کارمزد پلتفرم از کل مبلغ فاکتور — فقط توسط پلتفرم قابل تغییر است', max_digits=5),
        ),
    ]
