# Generated by Django 5.2.14 on 2026-06-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_companyfinancialpolicy_payout_strategy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyMerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "ارسال نشده"),
                            ("submitted", "ارسال شده"),
                            ("under_review", "در حال بررسی"),
                            ("approved", "تأییدشده"),
                            ("rejected", "رد شده"),
                            ("change_requested", "درخواست تغییر"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("real_person", "شخص حقیقی"),
                            ("legal_entity", "شخص حقوقی"),
                        ],
                        max_length=20,
                    ),
                ),
                ("legal_company_name", models.CharField(blank=True, max_length=200)),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="شناسه ملی شرکت (اشخاص حقوقی) یا کد ملی مالک (اشخاص حقیقی)",
                        max_length=30,
                    ),
                ),
                ("economic_code", models.CharField(blank=True, max_length=20)),
                ("registration_number", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=15)),
                ("registered_address", models.TextField(blank=True)),
                ("company_phone", models.CharField(blank=True, max_length=20)),
                ("owner_full_name", models.CharField(blank=True, max_length=200)),
                ("owner_national_code", models.CharField(blank=True, max_length=15)),
                ("owner_mobile", models.CharField(blank=True, max_length=15)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_holder_name", models.CharField(blank=True, max_length=200)),
                (
                    "shaba_number",
                    models.CharField(
                        blank=True, help_text="شماره شبا: IR + 24 رقم", max_length=26
                    ),
                ),
                ("bank_account_number", models.CharField(blank=True, max_length=30)),
                (
                    "bank_card_number",
                    models.CharField(
                        blank=True,
                        help_text="16 رقمی — در نمایش ماسک می\u200cشود",
                        max_length=20,
                    ),
                ),
                (
                    "national_card_image",
                    models.FileField(
                        blank=True,
                        help_text="تصویر کارت ملی مالک/نماینده — jpg, png, pdf",
                        null=True,
                        upload_to="companies/kyc/national_card/",
                    ),
                ),
                (
                    "business_license_image",
                    models.FileField(
                        blank=True,
                        help_text="جواز کسب یا پروانه فعالیت (اختیاری)",
                        null=True,
                        upload_to="companies/kyc/business_license/",
                    ),
                ),
                (
                    "latest_official_newspaper_image",
                    models.FileField(
                        blank=True,
                        help_text="آخرین آگهی روزنامه رسمی (اشخاص حقوقی — اختیاری)",
                        null=True,
                        upload_to="companies/kyc/newspaper/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to="tenants.company",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_merchant_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Merchant Profile",
                "verbose_name_plural": "Company Merchant Profiles",
            },
        ),
        migrations.CreateModel(
            name="CompanyMerchantProfileChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of all proposed text field values.",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأییدشده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "national_card_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="companies/kyc/change_requests/national_card/",
                    ),
                ),
                (
                    "business_license_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="companies/kyc/change_requests/business_license/",
                    ),
                ),
                (
                    "latest_official_newspaper_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="companies/kyc/change_requests/newspaper/",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile_change_requests",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_merchant_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="tenants.companymerchantprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_merchant_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Profile Change Request",
                "ordering": ["-created_at"],
            },
        ),
    ]
