# Generated by Django 5.1.3 on 2026-06-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderstatuslog_new_status_and_more'),
        ('tenants', '0003_company_merchant_profile_p5'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام فیلد، مثلاً «وضعیت گارانتی»', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'متن آزاد'), ('number', 'عدد'), ('checkbox', 'بلی/خیر'), ('select', 'لیست انتخابی')], default='text', max_length=20)),
                ('select_options', models.TextField(blank=True, help_text='گزینه\u200cها برای نوع لیست انتخابی، با کاما جدا کنید. مثال: گارانتی دارد,گارانتی ندارد,نامشخص')),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Custom Order Field',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tenants.ordercustomfield')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='orders.order')),
            ],
            options={
                'verbose_name': 'Custom Order Field Value',
                'unique_together': {('order', 'field')},
            },
        ),
    ]
