# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Gateway-assigned reference/authority.', max_length=100)),
                ('tracking_code', models.CharField(blank=True, help_text='Final tracking code after successful payment.', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('redirected', 'Redirected to Gateway'), ('callback_received', 'Callback Received'), ('verified', 'Verified'), ('failed', 'Failed')], default='started', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, help_text='Reference ID from gateway for this attempt.', max_length=200)),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect customer to gateway.')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw response from gateway.')),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'ZarinPal'), ('idpay', 'IDPay'), ('nextpay', 'NextPay'), ('fake', 'Fake (Testing)'), ('manual', 'Manual')], max_length=20)),
                ('merchant_id', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('callback_url', models.URLField(blank=True, help_text='Callback URL for payment verification.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'unique_together': {('company', 'gateway_type')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentgateway'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_2bfc7c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'invoice'], name='payments_pa_company_e146bf_idx'),
        ),
    ]
