# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMasterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Event key matching NotificationSetting / PlatformSMSMessageTypeSetting keys.', max_length=80, unique=True)),
                ('scope', models.CharField(choices=[('company', 'شرکت (پرداخت شرکت)'), ('platform', 'پلتفرم (پرداخت مالک)')], default='company', max_length=10)),
                ('recipient_type', models.CharField(choices=[('customer', 'مشتری'), ('technician', 'نیروی خدماتی'), ('admin', 'مدیر شرکت'), ('platform_admin', 'مدیر پلتفرم')], default='customer', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('template_text', models.TextField(help_text='Django template syntax. Variables: {{ company_name }}, {{ customer_name }}, etc.')),
                ('allowed_variables', models.TextField(blank=True, help_text='Comma-separated list of supported variables for this template.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Master Template',
                'verbose_name_plural': 'SMS Master Templates',
                'ordering': ['scope', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('kavenegar', 'Kavenegar'), ('ghasedak', 'Ghasedak'), ('melipayamak', 'MeliPayamak'), ('fake', 'Fake (Testing)')], max_length=20)),
                ('api_key', models.CharField(max_length=300)),
                ('sender_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['company_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('company_registered', 'ثبت\u200cنام شرکت جدید'), ('company_activated', 'فعال\u200cسازی شرکت'), ('company_rejected', 'رد شرکت'), ('company_admin_password_reset', 'بازنشانی رمز عبور مدیر'), ('operator_created', 'ایجاد اپراتور'), ('technician_created', 'ایجاد نیروی خدماتی'), ('technician_status_changed', 'تغییر وضعیت نیروی خدماتی'), ('technician_wage_percent_changed', 'تغییر درصد اجرت نیرو'), ('service_category_created', 'ایجاد رسته خدمات'), ('service_item_created', 'ایجاد آیتم خدمات'), ('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_created_customer', 'سفارش جدید - مشتری'), ('order_available_technician', 'سفارش جدید برای نیروها'), ('order_assigned_technician', 'تخصیص سفارش به نیرو'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_started', 'شروع سفارش'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_customer', 'درخواست لغو توسط مشتری'), ('order_cancel_requested_admin', 'درخواست لغو سفارش - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - نیرو'), ('order_cancel_rejected_technician', 'رد لغو - نیرو'), ('order_cancelled', 'لغو سفارش'), ('order_rescheduled', 'تغییر زمان سفارش'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('invoice_sent_customer', 'ارسال فاکتور - مشتری'), ('invoice_paid_customer', 'پرداخت فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('wallet_charged', 'شارژ کیف پول پیامک'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک'), ('sms_template_change_requested', 'درخواست تغییر قالب پیامک'), ('sms_template_change_approved', 'تأیید تغییر قالب پیامک'), ('sms_template_change_rejected', 'رد تغییر قالب پیامک'), ('sms_outbox_failed', 'خطا در ارسال پیامک'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک'), ('subscription_expired_admin', 'پایان اشتراک'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('template_text', models.TextField(help_text='Django template syntax. Example: {{ order_id }}, {{ customer_name }}')),
                ('is_active', models.BooleanField(default=True)),
                ('send_start_time', models.TimeField(blank=True, null=True)),
                ('send_end_time', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SMSOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(blank=True, choices=[('company_registered', 'ثبت\u200cنام شرکت جدید'), ('company_activated', 'فعال\u200cسازی شرکت'), ('company_rejected', 'رد شرکت'), ('company_admin_password_reset', 'بازنشانی رمز عبور مدیر'), ('operator_created', 'ایجاد اپراتور'), ('technician_created', 'ایجاد نیروی خدماتی'), ('technician_status_changed', 'تغییر وضعیت نیروی خدماتی'), ('technician_wage_percent_changed', 'تغییر درصد اجرت نیرو'), ('service_category_created', 'ایجاد رسته خدمات'), ('service_item_created', 'ایجاد آیتم خدمات'), ('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_created_customer', 'سفارش جدید - مشتری'), ('order_available_technician', 'سفارش جدید برای نیروها'), ('order_assigned_technician', 'تخصیص سفارش به نیرو'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_started', 'شروع سفارش'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_customer', 'درخواست لغو توسط مشتری'), ('order_cancel_requested_admin', 'درخواست لغو سفارش - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - نیرو'), ('order_cancel_rejected_technician', 'رد لغو - نیرو'), ('order_cancelled', 'لغو سفارش'), ('order_rescheduled', 'تغییر زمان سفارش'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('invoice_sent_customer', 'ارسال فاکتور - مشتری'), ('invoice_paid_customer', 'پرداخت فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('wallet_charged', 'شارژ کیف پول پیامک'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک'), ('sms_template_change_requested', 'درخواست تغییر قالب پیامک'), ('sms_template_change_approved', 'تأیید تغییر قالب پیامک'), ('sms_template_change_rejected', 'رد تغییر قالب پیامک'), ('sms_outbox_failed', 'خطا در ارسال پیامک'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک'), ('subscription_expired_admin', 'پایان اشتراک'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('message_length_snapshot', models.PositiveIntegerField(default=0)),
                ('sms_parts_snapshot', models.PositiveIntegerField(default=0)),
                ('sms_cost_rial_snapshot', models.BigIntegerField(default=0)),
                ('pricing_characters_per_sms_snapshot', models.PositiveIntegerField(default=0)),
                ('pricing_price_per_sms_rial_snapshot', models.PositiveIntegerField(default=0)),
                ('pricing_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'در صف ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شده'), ('delivered', 'ارسال موفق'), ('failed', 'ارسال ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sending_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('send_at', models.DateTimeField(blank=True, help_text='Scheduled send time. Empty means send as soon as possible.', null=True)),
                ('order_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('invoice_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms.smsprovider')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='sms.smstemplate')),
            ],
            options={
                'verbose_name': 'SMS Outbox',
                'verbose_name_plural': 'SMS Outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplateChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=80)),
                ('current_template_text', models.TextField(blank=True, help_text='Snapshot of the template text at request time.')),
                ('requested_template_text', models.TextField(help_text='The new text requested by company admin.')),
                ('requested_tone', models.CharField(choices=[('formal', 'رسمی'), ('friendly', 'دوستانه'), ('short', 'کوتاه و عملیاتی'), ('detailed', 'مفصل و توضیحی'), ('custom', 'سفارشی')], default='custom', max_length=10)),
                ('note', models.TextField(blank=True, help_text="Company admin's reason/note for the change.")),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, help_text="Platform owner's response/note on approval or rejection.")),
                ('approved_template_text', models.TextField(blank=True, help_text='Final text approved/corrected by platform owner. May differ from requested_template_text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_template_change_requests', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sms_template_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sms_template_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Template Change Request',
                'verbose_name_plural': 'SMS Template Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_sms_template_per_company'),
        ),
        migrations.AddIndex(
            model_name='smsoutbox',
            index=models.Index(fields=['company', 'status', 'send_at'], name='sms_outbox_company_due_idx'),
        ),
        migrations.AddIndex(
            model_name='smsoutbox',
            index=models.Index(fields=['company', 'phone_number', 'template_key'], name='sms_outbox_company_phone_idx'),
        ),
    ]
