# Generated by Django 5.2.14 on 2026-06-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_sms_inbox_conversation'),
        ('tenants', '0003_company_merchant_profile_p5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsinbox',
            name='company',
            field=models.ForeignKey(blank=True, help_text='شرکتی که این پیام به آن تعلق دارد (از طریق تطبیق با Outbox)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_inbox_messages', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='smsinbox',
            name='match_status',
            field=models.CharField(choices=[('matched', 'تطبیق داده شده'), ('unmatched', 'بدون تطبیق'), ('ambiguous', 'مبهم (چند شرکت)')], db_index=True, default='unmatched', help_text='وضعیت تطبیق با پیام ارسالی', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsinbox',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='شناسه پیام در سیستم Provider (برای جلوگیری از ثبت تکراری)', max_length=100),
        ),
        migrations.AlterField(
            model_name='smsinbox',
            name='rating_value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='مقدار امتیاز نظرسنجی (1 تا 5)، فقط زمانی پر می\u200cشود که response_type=survey_rating', null=True),
        ),
        migrations.AlterField(
            model_name='smsinbox',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='پیلود خام دریافتی از Provider (برای بررسی و رفع خطا)'),
        ),
        migrations.AlterField(
            model_name='smsinbox',
            name='response_type',
            field=models.CharField(choices=[('survey_rating', 'امتیاز نظرسنجی'), ('customer_message', 'پیام مشتری'), ('unknown', 'نامشخص')], db_index=True, default='unknown', help_text='نوع پاسخ تشخیص\u200cداده\u200cشده', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsmastertemplateproviderconfig',
            name='provider_setting_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='FK to PlatformSMSProviderSetting.id', null=True),
        ),
        migrations.AlterField(
            model_name='smsmastertemplateproviderconfig',
            name='send_mode',
            field=models.CharField(choices=[('text', 'ارسال متن ساده'), ('pattern', 'ارسال پترن/خدماتی')], default='pattern', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='template_key',
            field=models.CharField(blank=True, choices=[('company_registered', 'ثبت\u200cنام شرکت جدید'), ('company_activated', 'فعال\u200cسازی شرکت'), ('company_rejected', 'رد شرکت'), ('company_admin_login', 'ورود مدیر شرکت'), ('company_admin_password_reset', 'بازنشانی رمز عبور مدیر'), ('operator_created', 'ایجاد اپراتور'), ('technician_created', 'ایجاد نیروی خدماتی'), ('technician_login', 'ورود نیروی خدماتی'), ('company_user_password_reset', 'بازیابی رمز کاربر شرکت'), ('user_mobile_verification', 'تأیید شماره همراه کاربر'), ('technician_status_changed', 'تغییر وضعیت نیروی خدماتی'), ('technician_wage_percent_changed', 'تغییر درصد اجرت نیرو'), ('service_category_created', 'ایجاد رسته خدمات'), ('service_item_created', 'ایجاد آیتم خدمات'), ('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_created_customer', 'سفارش جدید - مشتری'), ('order_available_technician', 'سفارش جدید برای نیروها'), ('order_assigned_technician', 'تخصیص سفارش به نیرو'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_rejected_technician', 'رد سفارش توسط نیرو'), ('order_started', 'شروع سفارش'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_customer', 'درخواست لغو توسط مشتری'), ('order_cancel_requested_admin', 'درخواست لغو سفارش - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - نیرو'), ('order_cancel_rejected_technician', 'رد لغو - نیرو'), ('order_cancelled', 'لغو سفارش'), ('order_rescheduled', 'تغییر زمان سفارش'), ('invoice_created', 'ایجاد فاکتور'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('invoice_sent_customer', 'ارسال فاکتور - مشتری'), ('invoice_paid_customer', 'پرداخت فاکتور - مشتری'), ('invoice_cancelled', 'لغو فاکتور'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('wallet_charged', 'شارژ کیف پول پیامک'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک'), ('sms_template_change_requested', 'درخواست تغییر قالب پیامک'), ('sms_template_change_approved', 'تأیید تغییر قالب پیامک'), ('sms_template_change_rejected', 'رد تغییر قالب پیامک'), ('sms_outbox_failed', 'خطا در ارسال پیامک'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک'), ('subscription_expired_admin', 'پایان اشتراک'), ('subscription_renewed_admin', 'شارژ/تمدید اشتراک'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('discount_code_customer', 'کد تخفیف - مشتری')], max_length=80),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('company_registered', 'ثبت\u200cنام شرکت جدید'), ('company_activated', 'فعال\u200cسازی شرکت'), ('company_rejected', 'رد شرکت'), ('company_admin_login', 'ورود مدیر شرکت'), ('company_admin_password_reset', 'بازنشانی رمز عبور مدیر'), ('operator_created', 'ایجاد اپراتور'), ('technician_created', 'ایجاد نیروی خدماتی'), ('technician_login', 'ورود نیروی خدماتی'), ('company_user_password_reset', 'بازیابی رمز کاربر شرکت'), ('user_mobile_verification', 'تأیید شماره همراه کاربر'), ('technician_status_changed', 'تغییر وضعیت نیروی خدماتی'), ('technician_wage_percent_changed', 'تغییر درصد اجرت نیرو'), ('service_category_created', 'ایجاد رسته خدمات'), ('service_item_created', 'ایجاد آیتم خدمات'), ('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_created_customer', 'سفارش جدید - مشتری'), ('order_available_technician', 'سفارش جدید برای نیروها'), ('order_assigned_technician', 'تخصیص سفارش به نیرو'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_rejected_technician', 'رد سفارش توسط نیرو'), ('order_started', 'شروع سفارش'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_customer', 'درخواست لغو توسط مشتری'), ('order_cancel_requested_admin', 'درخواست لغو سفارش - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - نیرو'), ('order_cancel_rejected_technician', 'رد لغو - نیرو'), ('order_cancelled', 'لغو سفارش'), ('order_rescheduled', 'تغییر زمان سفارش'), ('invoice_created', 'ایجاد فاکتور'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('invoice_sent_customer', 'ارسال فاکتور - مشتری'), ('invoice_paid_customer', 'پرداخت فاکتور - مشتری'), ('invoice_cancelled', 'لغو فاکتور'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('wallet_charged', 'شارژ کیف پول پیامک'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک'), ('sms_template_change_requested', 'درخواست تغییر قالب پیامک'), ('sms_template_change_approved', 'تأیید تغییر قالب پیامک'), ('sms_template_change_rejected', 'رد تغییر قالب پیامک'), ('sms_outbox_failed', 'خطا در ارسال پیامک'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک'), ('subscription_expired_admin', 'پایان اشتراک'), ('subscription_renewed_admin', 'شارژ/تمدید اشتراک'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('discount_code_customer', 'کد تخفیف - مشتری')], max_length=80),
        ),
    ]
