# Generated by Django 5.2.14 on 2026-06-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('segment', 'گزارش هدفمند'), ('single_customer', 'مشتری خاص'), ('manual', 'دستی')], db_index=True, default='segment', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('queued', 'در صف ارسال'), ('sent', 'ارسال شده'), ('partial', 'ارسال ناقص'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('max_discount_rial', models.PositiveBigIntegerField(default=300000)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('message_template', models.TextField(blank=True)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('recipient_total', models.PositiveIntegerField(default=0)),
                ('excluded_total', models.PositiveIntegerField(default=0)),
                ('code_total', models.PositiveIntegerField(default=0)),
                ('sms_queued_total', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('code_masked', models.CharField(max_length=16)),
                ('percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('max_discount_rial', models.PositiveBigIntegerField(default=300000)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('created', 'ساخته شده'), ('sms_queued', 'پیامک در صف'), ('used', 'استفاده شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], db_index=True, default='created', max_length=20)),
                ('sms_outbox_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('used_invoice_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('used_discount_amount_rial', models.PositiveBigIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='reports.discountcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('last_address_snapshot', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('selected', 'انتخاب شده'), ('excluded', 'حذف شده'), ('code_created', 'کد ساخته شد'), ('sms_queued', 'پیامک در صف'), ('failed', 'ناموفق')], db_index=True, default='selected', max_length=20)),
                ('sms_outbox_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('excluded_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('excluded_by_username', models.CharField(blank=True, max_length=150)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=250)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='reports.discountcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='reports.discountcode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('orders_summary', 'Orders Summary'), ('revenue', 'Revenue Report'), ('technician_performance', 'Technician Performance'), ('customer_activity', 'Customer Activity')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discountcampaign',
            index=models.Index(fields=['company', 'status', 'created_at'], name='disc_campaign_company_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcampaign',
            index=models.Index(fields=['company', 'source'], name='disc_campaign_source_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['company', 'phone_number', 'status'], name='disc_code_phone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['company', 'expires_at'], name='disc_code_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('company', 'code_hash'), name='unique_discount_code_hash_per_company'),
        ),
        migrations.AddIndex(
            model_name='discountcampaignrecipient',
            index=models.Index(fields=['company', 'campaign', 'status'], name='disc_rec_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcampaignrecipient',
            index=models.Index(fields=['company', 'phone_number'], name='disc_rec_phone_idx'),
        ),
    ]
