# Generated by Django 5.2.14 on 2026-06-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaignAllowedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('normalized_phone', models.CharField(db_index=True, max_length=20)),
                ('customer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_invoice_id', models.PositiveIntegerField(blank=True, null=True)),
                ('used_discount_amount_rial', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='custom_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='discountcampaign',
            index=models.Index(fields=['company', 'custom_code'], name='disc_campaign_code_idx'),
        ),
        migrations.AddField(
            model_name='discountcampaignallowedphone',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_phones', to='reports.discountcampaign'),
        ),
        migrations.AddField(
            model_name='discountcampaignallowedphone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company'),
        ),
        migrations.AddIndex(
            model_name='discountcampaignallowedphone',
            index=models.Index(fields=['company', 'campaign', 'normalized_phone'], name='disc_allowed_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='discountcampaignallowedphone',
            constraint=models.UniqueConstraint(fields=('campaign', 'normalized_phone'), name='unique_allowed_phone_per_campaign'),
        ),
    ]
