# Generated by Django 5.2.14 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_available', 'Order Available'), ('order_assigned', 'Order Assigned'), ('order_accepted', 'Order Accepted'), ('order_completed', 'Order Completed'), ('order_cancel_requested', 'Order Cancel Requested'), ('order_cancel_approved', 'Order Cancel Approved'), ('order_cancel_rejected', 'Order Cancel Rejected'), ('invoice_issued', 'Invoice Issued'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=100)),
                ('target_app', models.CharField(blank=True, max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('recorded', 'ثبت شده'), ('dispatched', 'پردازش شده'), ('skipped', 'رد شده'), ('failed', 'ناموفق')], db_index=True, default='recorded', max_length=20)),
                ('result_message', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(choices=[('company_registered', 'ثبت\u200cنام شرکت جدید'), ('company_activated', 'فعال\u200cسازی شرکت'), ('company_rejected', 'رد شرکت'), ('company_admin_login', 'ورود مدیر شرکت'), ('company_admin_password_reset', 'بازنشانی رمز عبور مدیر'), ('operator_created', 'ایجاد اپراتور'), ('technician_created', 'ایجاد نیروی خدماتی'), ('technician_login', 'ورود نیروی خدماتی'), ('technician_status_changed', 'تغییر وضعیت نیروی خدماتی'), ('technician_wage_percent_changed', 'تغییر درصد اجرت نیرو'), ('service_category_created', 'ایجاد رسته خدمات'), ('service_item_created', 'ایجاد آیتم خدمات'), ('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_created_customer', 'سفارش جدید - مشتری'), ('order_available_technician', 'سفارش جدید برای نیروها'), ('order_assigned_technician', 'تخصیص سفارش به نیرو'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_rejected_technician', 'رد سفارش توسط نیرو'), ('order_started', 'شروع سفارش'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_customer', 'درخواست لغو توسط مشتری'), ('order_cancel_requested_admin', 'درخواست لغو سفارش - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - نیرو'), ('order_cancel_rejected_technician', 'رد لغو - نیرو'), ('order_cancelled', 'لغو سفارش'), ('order_rescheduled', 'تغییر زمان سفارش'), ('invoice_created', 'ایجاد فاکتور'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('invoice_sent_customer', 'ارسال فاکتور - مشتری'), ('invoice_paid_customer', 'پرداخت فاکتور - مشتری'), ('invoice_cancelled', 'لغو فاکتور'), ('payment_started', 'شروع پرداخت'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('wallet_charged', 'شارژ کیف پول پیامک'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک'), ('sms_template_change_requested', 'درخواست تغییر قالب پیامک'), ('sms_template_change_approved', 'تأیید تغییر قالب پیامک'), ('sms_template_change_rejected', 'رد تغییر قالب پیامک'), ('sms_outbox_failed', 'خطا در ارسال پیامک'), ('sms_outbox_retried', 'تلاش مجدد ارسال پیامک'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک'), ('subscription_expired_admin', 'پایان اشتراک'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_key'],
            },
        ),
    ]
